# permissions for end users to view grafanas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-viewer-role
rules:
- apiGroups:
  - grafana.snappcloud.io
  resources:
  - grafanas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafana.snappcloud.io
  resources:
  - grafanas/status
  verbs:
  - get
